project:
  type: website
  output-dir: docs

website:
  title: "DBW"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


date-format: "D MMMM YYYY"


